version: '2'
services:
  vae-training:
    image: baxter_vae_collision
    command: python -m src.train --label self --env one_box_environment --use-cuda false
    volumes:
    - /home/nikhildas/workspace/baxter_vae_collision:/home/user/baxter_vae_collision
    environment:
    - NVIDIA_VISIBLE_DEVICES=0

