version: '2'
services:
  vae-training:
    build: .
    command: python -m src.train --label self --env one_box_environment --use-cuda true
    volumes:
    - /home/jamesdi/workspace/baxter_vae_collision:/home/user/baxter_vae_collision
    environment:
    - NVIDIA_VISIBLE_DEVICES=2

